### ISSUE TITLE
Usage with gatsby-plugin-offline

### ISSUE THREAD

**Issue by universse** [ryanashcraft/gatsby-plugin-amplitude-analytics#7]
Hi. This plugin doesn't seem to play well with gatsby-plugin-offline. I only got a blank page on subsequent page load after service worker is installed. I had to resort to using plugin gatsby-plugin-remove-serviceworker and the site works as normal again. Do you have any suggestion or workaround for this?

**Comment by ryanashcraft** [comment]
@universse I'm not sure. Can you provide some more info? Any logs? This plugin is mostly a fork of the google analytics gatsby plugin – any chance there's been a fix there we can apply to this project?

**Comment by universse** [comment]
Hi. Sorry it's been a while. There was no useful log that helped me debug so I switched to dynamically importing amplitude-js using gatsby-browser api instead and things seem to be going well.
