### ISSUE TITLE
Make amplitude available in develop

### ISSUE THREAD

**Issue by dangayle** [ryanashcraft/gatsby-plugin-amplitude-analytics#8]
Right now the entire thing is hard coded to only work on production:
https://github.com/ryanashcraft/gatsby-plugin-amplitude-analytics/blob/master/src/gatsby-ssr.js#L7

Can we make that optional, for debugging purposes?

**Comment by ryanashcraft** [comment]
@dangayle Submit a PR with a sensible API and I'll ship it.

**Comment by dangayle** [comment]
ok, I'll see if I can work that into my next sprint
