### ISSUE TITLE
logEvent

### ISSUE THREAD

**Issue by joeleduardo** [ryanashcraft/gatsby-plugin-amplitude-analytics#9]
It is possible use logEvents calls like...
`onclick="amplitude.getInstance().logEvent('ClickEvent')"`

Basically on gatsby website just explain how set up the plugin but anything else.

Thanks

**Comment by joeleduardo** [comment]
Finally i did this:

```
const App = () => {
    const [amplitude, setAmplitude] = useState(null)

    useEffect(() => {
        setAmplitude(window.amplitude)
    },[])

    const onClickHandler = () => {
        if(amplitude) {
            amplitude.getInstance().logEvent('MY_EVENT')
        }
    }

return (<div onClick={() => onClickHandler()}>Click</div>)
}

export default App
```

Thanks

**Comment by ryanashcraft** [comment]
Glad you got this figured out. You don't really need to set amplitude in React state, you can simply store it as a global variable in your code or rely on it existing in the global window namespace.
